spring:
  application:
    name: fescart-item
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.232.128:3306/fescar-item?useUnicode=true&characterEncoding=UTF-8&SERVERtIMEZONE=UTC
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
#  main:
#    allow-bean-definition-overriding: true


server:
  port: 18082
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

feign:
  hystrix:
    enabled: true
# hystrix配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillIseconds: 10000
          strategy: SEMAPHORE
