server:
  port: 18081
spring:
  application:
    name: business
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.232.128:3306/fescar-business?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
#  main:
#    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

#读取超时设置
ribbon:
  ReadTimeout: 30000
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
          strategy: SEMAPHORE