spring:
  application:
    name: eureka-server-test1

server:
  port: 8001

eureka:
  instance:
    hostname: eureka-server1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server2:8002/eureka/,http://eureka-server3:8003/eureka/
