server:
  port: 7001
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka
    register-with-eureka: false  #是否将自己注册到eureka中
    fetch-registry: false        #是否从eureka中获取信息

spring:
  application:
    name: fescar-eureka