spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" # 跨域处理  允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - UPDATE
              - DELETE
      routes:
        - id: changgou_goods_routes
          #uri: http://localhost:18081
          #下面这里使用了负载均衡，就不是锁定单个端口了
          uri: lb://goods
          predicates:
            # 下面这个主要是为了将cloud.play.com的请求交给http://localhost:18081处理
            #- Host=cloud.play.com**
            # 下面设置的请求一律打到http://localhost:18081里面去
            - Path=/api/album/**,/api/brand/**,/api/cache/**,/api/categoryBrand/**,/api/category/**,/api/para/**,/api/pref/**,/api/sku/**,/api/spec/**,/api/spu/**,/api/stockBack/**,/api/template/**
          filters:
            # 自动帮你加一个前缀,不用自己写
            #- PrefixPath=/brand
            # 去掉第一个前缀，以/作为分隔
            - StripPrefix=1
            - name: RequestRateLimiter #请求数限流，名称不能随便写，使用默认的factory
              args:
                key-resolver: "#{@ipKeyResolver}"
                # 每秒钟只允许有一个请求
                redis-rate-limiter.replenishRate: 1
                # 允许并发有4个请求【宽限的个数】，令牌桶的容量，允许在一秒钟内完成的最大请求数
                redis-rate-limiter.burstCapacity: 4
        - id: changgou_user_routes
          uri: lb://user
          predicates:
            - Path=/api/user/**,/api/cities/**,/api/address/**,/api/provinces/**,/api/areas/**
          filters:
            - StripPrefix=1
        - id: changgou_order_routes
          uri: lb://order
          predicates:
            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
          filters:
            - StripPrefix=1
  redis:
    host: 192.168.232.128
    port: 6379
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true

